### ISSUE TITLE
Trust wallet

### ISSUE THREAD

**Issue by KaaseNreaL** [conda-forge/bytecode-feedstock#10]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Trust wallet 

### Installed packages

```shell
Trust wallet
```

### Environment info

```shell
Trust wallet sending BTC
```

**Comment by KaaseNreaL** [comment]
Just the fee temt out the smal Bayer's

**Comment by MatthieuDartiailh** [comment]
I have no idea what you mean but it seems unrelated to this package
